// List of preset professions for service providers
export const professions = [
  'Electrician',
  'Plumber',
  'Builder',
  'Carpenter',
  'Painter',
  'Mechanic',
  'Cleaner',
  'Tiler',
  'Gardener',
  'Handyman',
  'Locksmith',
  'Appliance Repair',
  'Roofer',
  'Welder',
  'HVAC Technician',
  'Landscaper',
  'Pest Control',
  'Security System Installer',
  'Flooring Specialist',
  'Drywall Installer',
  'Concrete Specialist',
  'Fence Installer',
  'Window Installer',
  'Cabinetmaker',
  'Furniture Assembler',
  'Moving Service',
  'Junk Removal',
  'Pool Maintenance',
  'Pressure Washer',
  'Gutter Cleaner',
  'Solar Panel Installer',
  'Home Inspector',
  'Interior Designer',
  'Decorator',
  'Upholsterer',
  'Seamstress/Tailor',
  'Computer Repair',
  'TV Mounting',
  'Smart Home Installer',
  'Lawn Care Specialist'
];
